AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  java-lambda-metrics

  Sample SAM Template for java-lambda-metrics

Resources:
  SampleMetricsApp:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: SampleMetricsApp
      Handler: metrics.App::handleRequest
      Runtime: java11
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - CloudWatchAgentServerPolicy
      Layers:
        - !FindInMap [RegionMap, !Ref "AWS::Region", layer]
      Events:
        getEndpoint:
          Type: Api 
          Properties:
            Path: /
            Method: get

Mappings:
  RegionMap:
    ap-northeast-1:
      layer: "arn:aws:lambda:ap-northeast-1:901920570463:layer:aws-otel-collector-ver-0-27-0:1"
    ap-northeast-2:
      layer: "arn:aws:lambda:ap-northeast-2:901920570463:layer:aws-otel-collector-ver-0-27-0:1"
    ap-south-1:
      layer: "arn:aws:lambda:ap-south-1:901920570463:layer:aws-otel-collector-ver-0-27-0:1"
    ap-southeast-1:
      layer: "arn:aws:lambda:ap-southeast-1:901920570463:layer:aws-otel-collector-ver-0-27-0:1"
    ap-southeast-2:
      layer: "arn:aws:lambda:ap-southeast-2:901920570463:layer:aws-otel-collector-ver-0-27-0:1"
    ca-central-1:
      layer: "arn:aws:lambda:ca-central-1:901920570463:layer:aws-otel-collector-ver-0-27-0:1"
    eu-central-1:
      layer: "arn:aws:lambda:eu-central-1:901920570463:layer:aws-otel-collector-ver-0-27-0:1"
    eu-north-1:
      layer: "arn:aws:lambda:eu-north-1:901920570463:layer:aws-otel-collector-ver-0-27-0:1"
    eu-west-1:
      layer: "arn:aws:lambda:eu-west-1:901920570463:layer:aws-otel-collector-ver-0-27-0:1"
    eu-west-2:
      layer: "arn:aws:lambda:eu-west-2:901920570463:layer:aws-otel-collector-ver-0-27-0:1"
    eu-west-3:
      layer: "arn:aws:lambda:eu-west-3:901920570463:layer:aws-otel-collector-ver-0-27-0:1"
    sa-east-1:
      layer: "arn:aws:lambda:sa-east-1:901920570463:layer:aws-otel-collector-ver-0-27-0:1"
    us-east-1:
      layer: "arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-collector-ver-0-27-0:1"
    us-east-2:
      layer: "arn:aws:lambda:us-east-2:901920570463:layer:aws-otel-collector-ver-0-27-0:1"
    us-west-1:
      layer: "arn:aws:lambda:us-west-1:901920570463:layer:aws-otel-collector-ver-0-27-0:1"
    us-west-2:
      layer: "arn:aws:lambda:us-west-2:901920570463:layer:aws-otel-collector-ver-0-27-0:1"